config/routes.rb
GridironGuru::Application.routes.draw do
  root to: 'site#root'

  resources :users, except: [:index, :destroy], param: :username do
    resource :session, only: :index
  end

  resources :leagues, only: [:index, :show, :create, :update, :destroy] do

    namespace :api, defaults: { format: :json } do
      resources :teams, only: [:index, :show, :create, :update, :destroy]
      resources :add_drops, only: [:create]
      resources :players, only: [:index, :show]
      resources :trades, only: [:create, :update, :destroy]
      resources :roster_spots, only: [:index, :create, :update, :destroy]
      resources :matchups, only: [:show, :index]
    end
  end

  resource :session, only: [:new, :create, :destroy]
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)      not null
#  email           :string(255)      not null
#  first_name      :string(255)      not null
#  last_name       :string(255)      not null
#  password_digest :string(255)      not null
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  validates :username, presence: true, uniqueness: true
  validates :username, format: { with: /\A[a-z]+[0-9]*[a-z]*\z/i,
                                 message: "must start with a letter" }
  validates :email, format: { with: /\A.+@.+\..+\z/ }
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password

  has_many :teams, dependent: :destroy
  has_many :managed_leagues,
           foreign_key: :manager_id,
           class_name: "League"
  has_many :leagues,
           through: :teams,
           source: :league
  has_many :sessions

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    user && user.is_password?(password) ? user : nil
  end

  def password=(secret)
    @password = secret
    self.password_digest = BCrypt::Password.create(secret)
  end

  def is_password?(secret)
    BCrypt::Password.new(self.password_digest).is_password?(secret)
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:edit, :update]

  def show
    if logged_in?
      find_user
      render :show
    else
      redirect_to new_session_url
    end
  end

  def new
    if logged_in?
      redirect_to root_url
    else
      @user = User.new

      render :new
    end
  end

  def create
    @user = User.new(user_params)

    if params[:user][:password] == params[:user][:password_confirm]
      if @user.save
        sign_in(@user)
        set_flash(:success, "You have successfully created an account!")

        redirect_to root_url
      else
        set_flash_now(:error, @user.errors.full_messages)

        render :new
      end
    else
      set_flash_now(:error, "Password fields must match")

      render :new
    end
  end

  def edit
    render :edit
  end

  def update
    if params[:user][:password] == params[:user][:password_confirm]
      if @user.update_attributes(user_params)
        sign_in(@user)
        set_flash(:success, "Account successfully updated")

        redirect_to user_url(@user)
      else
        set_flash_now(:error, @user.errors.full_messages)

        render :edit
      end
    else
      set_flash_now(:error, "Password fields must match")

      render :edit
    end
  end

  private

    def user_params
      params.require(:user).permit(:username, :password, :email, :first_name, :last_name)
    end

    def find_user
      @user = User.find_by_username(params[:username]) || User.find(params[:username])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class='col-sm-10'>
  <form action="<%= url %>" method="POST" accept-charset="utf-8" role='form' class='form-horizontal'>
    <%= render 'layouts/authenticity_token' %>
    <%= render 'layouts/patch_request' if request == :patch %>

    <div class='form-group'>
      <label for="username" class="col-sm-3 control-label">Username</label>
      <div class='col-sm-8'>
        <input type="text" name="user[username]" value="<%= @user.username %>" class='form-control' id='username'>
      </div>
    </div>
    <div class='form-group'>
      <label for="email" class="col-sm-3 control-label">Email</label>
      <div class='col-sm-8'>
        <input type="email" name="user[email]" value="<%= @user.email %>" class='form-control' id='email'>
      </div>
    </div>
    <div class='form-group'>
      <label for="first-name" class="col-sm-3 control-label">First Name</label>
      <div class='col-sm-8'>
        <input type="text" name="user[first_name]" value="<%= @user.first_name %>" class='form-control' id='first-name'>
      </div>
    </div>
    <div class='form-group'>
      <label for="last_name" class="col-sm-3 control-label">Last Name</label>
      <div class='col-sm-8'>
        <input type="text" name="user[last_name]" value="<%= @user.last_name %>" class='form-control' id='username'>
      </div>
    </div>
    <div class='form-group'>
      <label for="password" class="col-sm-3 control-label">Password</label>
      <div class='col-sm-8'>
        <input type="password" name="user[password]" class='form-control' id='username'>
      </div>
    </div>
    <div class='form-group'>
      <label for="password_confirm" class="col-sm-3 control-label">Confirm Password</label>
      <div class='col-sm-8'>
        <input type="password" name="user[password_confirm]" class='form-control' id='username'>
      </div>
    </div>

    <button class='btn btn-primary col-sm-offset-3'>Submit &rarr;</button>
  </form>
</div>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>

<%= render 'form', url: user_url(@user),
                   request: :patch %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form', url: users_url %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<% if @user == current_user %>
  <small><%= link_to "Edit your profile", edit_user_url(@user.username) %></small>
<% end %>

<h3>All Your Teams</h3>
<% @user.teams.each do |team| %>
  <p>
    <%= link_to team.name, league_team_url(team.league, team) %><br>
    <%= link_to team.league.name, league_url(team.league) %>
    <% if team.league.manager_id == @user.id %>
      <br>* Commissioner
    <% end %>
  </p>
<% end %>

<%= link_to "Join a league", leagues_url %><br>
<%= link_to "Create a league", new_league_url %>