config/routes.rb
GridironGuru::Application.routes.draw do
  root to: 'site#root'

  resources :users, except: [:index, :destroy], param: :username do
    resource :session, only: :index
  end

  resources :leagues, only: [:index, :show, :create, :update, :destroy] do

    namespace :api, defaults: { format: :json } do
      resources :teams, only: [:index, :show, :create, :update, :destroy]
      resources :add_drops, only: [:create]
      resources :players, only: [:index, :show]
      resources :trades, only: [:create, :update, :destroy]
      resources :roster_spots, only: [:index, :create, :update, :destroy]
      resources :matchups, only: [:show, :index]
    end
  end

  resource :session, only: [:new, :create, :destroy]
end

app/views/layouts/_authenticity_token.html.erb
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

app/views/layouts/_notices.html.erb
<% if flash[:info] %>
  <% flash[:info].each do |info| %>
    <p class="alert alert-info alert-dismissable"><%= info %></p>
  <% end %>
<% end %>
<% if flash[:success] %>
  <% flash[:success].each do |success| %>
    <p class="alert alert-success alert-dismissable"><%= success %></p>
  <% end %>
<% end %>
<% if flash[:warning] %>
  <% flash[:warning].each do |warning| %>
    <p class="alert alert-warning alert-dismissable"><%= warning %></p>
  <% end %>
<% end %>
<% if flash[:error] %>
  <% flash[:error].each do |error| %>
    <p class="alert alert-danger alert-dismissable"><%= error %></p>
  <% end %>
<% end %>

app/views/layouts/_patch_request.html.erb
<input type="hidden" name="_method" value="PATCH">

app/views/layouts/_player_actions.html.erb
<% if @team.players.include?(player) %>
  <a href='<%= team_add_drops_url(@team) %>'
     class='drop-player'
     data-id='<%= player.id %>'
     data-url='<%= league_team_url(@team.league, @team) %>'>
     <i class='icon-collapse-alt' style="font-size: 18px;"></i>
  </a>
<% else %>
  <a href='<%= team_add_drops_url(@team) %>'
     class='add-player'
     data-id='<%= player.id %>'
     data-url='<%= league_team_url(@team.league, @team) %>'>
     <i class='icon-expand-alt' style="font-size: 18px;"></i>
  </a>
<% end %>


<% if @team.watched_players.include?(player) %>
  <% watched_player_join = @watched_player_joins.find_by_player_id(player.id) %>

  <a href='<%= team_watched_player_url(@team, watched_player_join.id) %>'
     class='watch-player remove'
     data-id='<%= watched_player_join.id %>'>
     <i class='icon-eye-close' style="font-size: 15px;"></i>
  </a>
<% else %>
  <a href='<%= team_watched_players_url(@team) %>'
     class='watch-player add'
     data-id='<%= player.id %>'>
     <i class='icon-eye-open' style="font-size: 15px;"></i>
  </a>
<% end %>

app/views/layouts/_sign_in.html.erb
<form action="<%= session_url %>" method="POST" accept-charset="utf-8" class='navbar-form navbar-right' role='form'>
  <%= render 'layouts/authenticity_token' %>

  <input type="hidden" name="user[username]" value="test">
  <input type="hidden" name="user[password]" value="123456">

  <button class='btn btn-success btn-sm'>Demo User</button>
</form>

<form action="<%= session_url %>" method="POST" accept-charset="utf-8" class='navbar-form navbar-right' role='form'>
  <%= render 'layouts/authenticity_token' %>

  <div class='form-group'>
    <label class='sr-only' for='username'>Username</label>
      <input type="text" name="user[username]" id='username' placeholder="Enter username" class='form-control input-sm'>
  </div>
  <div class='form-group'>
    <label class='sr-only' for 'password'>Password</label>
      <input type="password" id='password' name="user[password]" placeholder="Password" class='form-control input-sm'>
  </div>

  <button type="submit" class='btn btn-default btn-sm'>Sign In</button>
</form>

app/views/layouts/_sign_out.html.erb
<form action="<%= session_url %>" class='navbar-form navbar-right' method="post">
    <%= render 'layouts/authenticity_token' %>
    <input name="_method" type="hidden" value="delete">

    <button class="btn btn-default btn-sm" type="submit"><span class='glyphicon glyphicon-off'></span> Sign Out</button>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fantasy Football</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>
  <nav class="navbar navbar-default shadow" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <strong><a class="navbar-brand" href="#">Gridiron<span class='glyphicon glyphicon-flash text-red'></span>Guru</a></strong>
      </div>

      <div class="collapse navbar-collapse">
        <% if @user = current_user %>
          <%= render 'layouts/sign_out' %>
          <ul class="nav navbar-nav navbar-right">
            <li><a>Welcome, <%= @user.first_name %><span class='caret'></span></a></li>
          </ul>
        <% else %>
          <%= render 'layouts/sign_in' %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Sign up", new_user_url %></li>
          </ul>
        <% end %>
      </div>
    </div>
  </nav>

  <div class='container no-padding'>
    <div class='center-block'>
      <% unless @user %>
        <div class='content shadow'>
          <form action="<%= session_url %>" method="POST" accept-charset="utf-8" role='form'>
            <%= render 'layouts/authenticity_token' %>

            <input type="hidden" name="user[username]" value="test">
            <input type="hidden" name="user[password]" value="123456">

            <button class='btn btn-lg btn-success btn-block'>Sign in as demo user</button>
          </form>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </div>
</body>
</html>